package metered

// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/metered.tmpl
// gowrap: http://github.com/hexdigest/gowrap

import (
	"context"

	"github.com/uber/cadence/common/config"
	"github.com/uber/cadence/common/log"
	"github.com/uber/cadence/common/metrics"
	"github.com/uber/cadence/common/persistence"
)

// meteredQueueManager implements persistence.QueueManager interface instrumented with rate limiter.
type meteredQueueManager struct {
	base
	wrapped persistence.QueueManager
}

// NewQueueManager creates a new instance of QueueManager with ratelimiter.
func NewQueueManager(
	wrapped persistence.QueueManager,
	metricClient metrics.Client,
	logger log.Logger,
	cfg *config.Persistence,
) persistence.QueueManager {
	return &meteredQueueManager{
		wrapped: wrapped,
		base: base{
			metricClient:                  metricClient,
			logger:                        logger,
			enableLatencyHistogramMetrics: cfg.EnablePersistenceLatencyHistogramMetrics,
			hostName:                      cfg.HostName,
		},
	}
}

func (c *meteredQueueManager) Close() {
	c.wrapped.Close()
	return
}

func (c *meteredQueueManager) DeleteMessageFromDLQ(ctx context.Context, request *persistence.DeleteMessageFromDLQRequest) (err error) {
	op := func() error {
		err = c.wrapped.DeleteMessageFromDLQ(ctx, request)
		c.emptyMetric("QueueManager.DeleteMessageFromDLQ", request, err, err)
		return err
	}

	err = c.call(metrics.PersistenceDeleteMessageFromDLQScope, op, getCustomMetricTags(request)...)
	return
}

func (c *meteredQueueManager) DeleteMessagesBefore(ctx context.Context, request *persistence.DeleteMessagesBeforeRequest) (err error) {
	op := func() error {
		err = c.wrapped.DeleteMessagesBefore(ctx, request)
		c.emptyMetric("QueueManager.DeleteMessagesBefore", request, err, err)
		return err
	}

	err = c.call(metrics.PersistenceDeleteMessagesBeforeScope, op, getCustomMetricTags(request)...)
	return
}

func (c *meteredQueueManager) EnqueueMessage(ctx context.Context, request *persistence.EnqueueMessageRequest) (err error) {
	op := func() error {
		err = c.wrapped.EnqueueMessage(ctx, request)
		c.emptyMetric("QueueManager.EnqueueMessage", request, err, err)
		return err
	}

	err = c.call(metrics.PersistenceEnqueueMessageScope, op, getCustomMetricTags(request)...)
	return
}

func (c *meteredQueueManager) EnqueueMessageToDLQ(ctx context.Context, request *persistence.EnqueueMessageToDLQRequest) (err error) {
	op := func() error {
		err = c.wrapped.EnqueueMessageToDLQ(ctx, request)
		c.emptyMetric("QueueManager.EnqueueMessageToDLQ", request, err, err)
		return err
	}

	err = c.call(metrics.PersistenceEnqueueMessageToDLQScope, op, getCustomMetricTags(request)...)
	return
}

func (c *meteredQueueManager) GetAckLevels(ctx context.Context, request *persistence.GetAckLevelsRequest) (gp1 *persistence.GetAckLevelsResponse, err error) {
	op := func() error {
		gp1, err = c.wrapped.GetAckLevels(ctx, request)
		c.emptyMetric("QueueManager.GetAckLevels", request, gp1, err)
		return err
	}

	err = c.call(metrics.PersistenceGetAckLevelsScope, op, getCustomMetricTags(request)...)
	return
}

func (c *meteredQueueManager) GetDLQAckLevels(ctx context.Context, request *persistence.GetDLQAckLevelsRequest) (gp1 *persistence.GetDLQAckLevelsResponse, err error) {
	op := func() error {
		gp1, err = c.wrapped.GetDLQAckLevels(ctx, request)
		c.emptyMetric("QueueManager.GetDLQAckLevels", request, gp1, err)
		return err
	}

	err = c.call(metrics.PersistenceGetDLQAckLevelsScope, op, getCustomMetricTags(request)...)
	return
}

func (c *meteredQueueManager) GetDLQSize(ctx context.Context, request *persistence.GetDLQSizeRequest) (gp1 *persistence.GetDLQSizeResponse, err error) {
	op := func() error {
		gp1, err = c.wrapped.GetDLQSize(ctx, request)
		c.emptyMetric("QueueManager.GetDLQSize", request, gp1, err)
		return err
	}

	err = c.call(metrics.PersistenceGetDLQSizeScope, op, getCustomMetricTags(request)...)
	return
}

func (c *meteredQueueManager) RangeDeleteMessagesFromDLQ(ctx context.Context, request *persistence.RangeDeleteMessagesFromDLQRequest) (err error) {
	op := func() error {
		err = c.wrapped.RangeDeleteMessagesFromDLQ(ctx, request)
		c.emptyMetric("QueueManager.RangeDeleteMessagesFromDLQ", request, err, err)
		return err
	}

	err = c.call(metrics.PersistenceRangeDeleteMessagesFromDLQScope, op, getCustomMetricTags(request)...)
	return
}

func (c *meteredQueueManager) ReadMessages(ctx context.Context, request *persistence.ReadMessagesRequest) (rp1 *persistence.ReadMessagesResponse, err error) {
	op := func() error {
		rp1, err = c.wrapped.ReadMessages(ctx, request)
		c.emptyMetric("QueueManager.ReadMessages", request, rp1, err)
		return err
	}

	err = c.call(metrics.PersistenceReadMessagesScope, op, getCustomMetricTags(request)...)
	return
}

func (c *meteredQueueManager) ReadMessagesFromDLQ(ctx context.Context, request *persistence.ReadMessagesFromDLQRequest) (rp1 *persistence.ReadMessagesFromDLQResponse, err error) {
	op := func() error {
		rp1, err = c.wrapped.ReadMessagesFromDLQ(ctx, request)
		c.emptyMetric("QueueManager.ReadMessagesFromDLQ", request, rp1, err)
		return err
	}

	err = c.call(metrics.PersistenceReadMessagesFromDLQScope, op, getCustomMetricTags(request)...)
	return
}

func (c *meteredQueueManager) UpdateAckLevel(ctx context.Context, request *persistence.UpdateAckLevelRequest) (err error) {
	op := func() error {
		err = c.wrapped.UpdateAckLevel(ctx, request)
		c.emptyMetric("QueueManager.UpdateAckLevel", request, err, err)
		return err
	}

	err = c.call(metrics.PersistenceUpdateAckLevelScope, op, getCustomMetricTags(request)...)
	return
}

func (c *meteredQueueManager) UpdateDLQAckLevel(ctx context.Context, request *persistence.UpdateDLQAckLevelRequest) (err error) {
	op := func() error {
		err = c.wrapped.UpdateDLQAckLevel(ctx, request)
		c.emptyMetric("QueueManager.UpdateDLQAckLevel", request, err, err)
		return err
	}

	err = c.call(metrics.PersistenceUpdateDLQAckLevelScope, op, getCustomMetricTags(request)...)
	return
}
